// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LoaderCssNamespace {
  export interface ILoaderCss {
    container: string;
    containerBlock: string;
    loader: string;
    'spinner-animation': string;
  }
}

declare const LoaderCssModule: LoaderCssNamespace.ILoaderCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LoaderCssNamespace.ILoaderCss;
};

export = LoaderCssModule;
