// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TooltipCssNamespace {
  export interface ITooltipCss {
    nowrap: string;
    trigger: string;
  }
}

declare const TooltipCssModule: TooltipCssNamespace.ITooltipCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TooltipCssNamespace.ITooltipCss;
};

export = TooltipCssModule;
