// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PushPostFormCssNamespace {
  export interface IPushPostFormCss {
    postType: string;
  }
}

declare const PushPostFormCssModule: PushPostFormCssNamespace.IPushPostFormCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PushPostFormCssNamespace.IPushPostFormCss;
};

export = PushPostFormCssModule;
