// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CardCssNamespace {
  export interface ICardCss {
    card: string;
  }
}

declare const CardCssModule: CardCssNamespace.ICardCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CardCssNamespace.ICardCss;
};

export = CardCssModule;
