// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NoticeCssNamespace {
  export interface INoticeCss {
    notice: string;
    noticeError: string;
    noticeInfo: string;
    noticeSuccess: string;
    noticeWarning: string;
  }
}

declare const NoticeCssModule: NoticeCssNamespace.INoticeCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NoticeCssNamespace.INoticeCss;
};

export = NoticeCssModule;
