// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageCssNamespace {
  export interface IPageCss {
    content: string;
    page: string;
    title: string;
  }
}

declare const PageCssModule: PageCssNamespace.IPageCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PageCssNamespace.IPageCss;
};

export = PageCssModule;
