// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IconCssNamespace {
  export interface IIconCss {
    animationSpin: string;
    border: string;
    icon: string;
    round: string;
    spinner: string;
  }
}

declare const IconCssModule: IconCssNamespace.IIconCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IconCssNamespace.IIconCss;
};

export = IconCssModule;
