// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ImageCssNamespace {
  export interface IImageCss {
    image: string;
    imageImg: string;
  }
}

declare const ImageCssModule: ImageCssNamespace.IImageCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ImageCssNamespace.IImageCss;
};

export = ImageCssModule;
