// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MaskedImageCssNamespace {
  export interface IMaskedImageCss {
    container: string;
    raw: string;
  }
}

declare const MaskedImageCssModule: MaskedImageCssNamespace.IMaskedImageCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MaskedImageCssNamespace.IMaskedImageCss;
};

export = MaskedImageCssModule;
