// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SvgCssNamespace {
  export interface ISvgCss {
    inline: string;
    svg: string;
  }
}

declare const SvgCssModule: SvgCssNamespace.ISvgCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SvgCssNamespace.ISvgCss;
};

export = SvgCssModule;
