// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TabNavigationCssNamespace {
  export interface ITabNavigationCss {
    link: string;
    linkActive: string;
    navigation: string;
  }
}

declare const TabNavigationCssModule: TabNavigationCssNamespace.ITabNavigationCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TabNavigationCssNamespace.ITabNavigationCss;
};

export = TabNavigationCssModule;
