// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonGroupCssNamespace {
  export interface IButtonGroupCss {
    alignCenter: string;
    alignLeft: string;
    alignRight: string;
    group: string;
  }
}

declare const ButtonGroupCssModule: ButtonGroupCssNamespace.IButtonGroupCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonGroupCssNamespace.IButtonGroupCss;
};

export = ButtonGroupCssModule;
