// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonCssNamespace {
  export interface IButtonCss {
    button: string;
    buttonPrimary: string;
  }
}

declare const ButtonCssModule: ButtonCssNamespace.IButtonCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonCssNamespace.IButtonCss;
};

export = ButtonCssModule;
