// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormControlsCssNamespace {
  export interface IFormControlsCss {
    controls: string;
  }
}

declare const FormControlsCssModule: FormControlsCssNamespace.IFormControlsCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormControlsCssNamespace.IFormControlsCss;
};

export = FormControlsCssModule;
