// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormTableGroupCssNamespace {
  export interface IFormTableGroupCss {
    card: string;
  }
}

declare const FormTableGroupCssModule: FormTableGroupCssNamespace.IFormTableGroupCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormTableGroupCssNamespace.IFormTableGroupCss;
};

export = FormTableGroupCssModule;
