// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormContentCssNamespace {
  export interface IFormContentCss {
    content: string;
  }
}

declare const FormContentCssModule: FormContentCssNamespace.IFormContentCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormContentCssNamespace.IFormContentCss;
};

export = FormContentCssModule;
