// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormFeedbackCssNamespace {
  export interface IFormFeedbackCss {
    td: string;
  }
}

declare const FormFeedbackCssModule: FormFeedbackCssNamespace.IFormFeedbackCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormFeedbackCssNamespace.IFormFeedbackCss;
};

export = FormFeedbackCssModule;
