// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormElementCssNamespace {
  export interface IFormElementCss {
    container: string;
    error: string;
    input: string;
  }
}

declare const FormElementCssModule: FormElementCssNamespace.IFormElementCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormElementCssNamespace.IFormElementCss;
};

export = FormElementCssModule;
