// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormCssNamespace {
  export interface IFormCss {
    form: string;
    table: string;
  }
}

declare const FormCssModule: FormCssNamespace.IFormCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormCssNamespace.IFormCss;
};

export = FormCssModule;
