// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InputColorCssNamespace {
  export interface IInputColorCss {
    colorPreview: string;
    input: string;
    inputWrapper: string;
    picker: string;
    wrapper: string;
  }
}

declare const InputColorCssModule: InputColorCssNamespace.IInputColorCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InputColorCssNamespace.IInputColorCss;
};

export = InputColorCssModule;
