// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InputUploadCssNamespace {
  export interface IInputUploadCss {
    add: string;
    container: string;
    element: string;
    image: string;
    remove: string;
  }
}

declare const InputUploadCssModule: InputUploadCssNamespace.IInputUploadCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InputUploadCssNamespace.IInputUploadCss;
};

export = InputUploadCssModule;
