// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InputRadioCssNamespace {
  export interface IInputRadioCss {
    element: string;
    input: string;
    label: string;
  }
}

declare const InputRadioCssModule: InputRadioCssNamespace.IInputRadioCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InputRadioCssNamespace.IInputRadioCss;
};

export = InputRadioCssModule;
