// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContentCssNamespace {
  export interface IContentCss {
    content: string;
  }
}

declare const ContentCssModule: ContentCssNamespace.IContentCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContentCssNamespace.IContentCss;
};

export = ContentCssModule;
