// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PushSettingsCssNamespace {
  export interface IPushSettingsCss {
    maskedBadge: string;
    maskedBadgeContainer: string;
  }
}

declare const PushSettingsCssModule: PushSettingsCssNamespace.IPushSettingsCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PushSettingsCssNamespace.IPushSettingsCss;
};

export = PushSettingsCssModule;
