// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PushSubscriptionCssNamespace {
  export interface IPushSubscriptionCss {
    controls: string;
    device: string;
    notifications: string;
    row: string;
    user: string;
  }
}

declare const PushSubscriptionCssModule: PushSubscriptionCssNamespace.IPushSubscriptionCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PushSubscriptionCssNamespace.IPushSubscriptionCss;
};

export = PushSubscriptionCssModule;
