// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ManifestSettingsCssNamespace {
  export interface IManifestSettingsCss {
    gtmTrackingCode: string;
  }
}

declare const ManifestSettingsCssModule: ManifestSettingsCssNamespace.IManifestSettingsCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ManifestSettingsCssNamespace.IManifestSettingsCss;
};

export = ManifestSettingsCssModule;
