// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageManifestCssNamespace {
  export interface IPageManifestCss {
    gtmTrackingCode: string;
  }
}

declare const PageManifestCssModule: PageManifestCssNamespace.IPageManifestCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PageManifestCssNamespace.IPageManifestCss;
};

export = PageManifestCssModule;
