// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageAboutCssNamespace {
    export interface IPageAboutCss {
        credits: string;
        footer: string;
        help: string;
        intro: string;
    }
}

declare const PageAboutCssModule: PageAboutCssNamespace.IPageAboutCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PageAboutCssNamespace.IPageAboutCss;
};

export = PageAboutCssModule;
