// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PagePushSubscriptionsCssNamespace {
  export interface IPagePushSubscriptionsCss {
    element: string;
    list: string;
  }
}

declare const PagePushSubscriptionsCssModule: PagePushSubscriptionsCssNamespace.IPagePushSubscriptionsCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PagePushSubscriptionsCssNamespace.IPagePushSubscriptionsCss;
};

export = PagePushSubscriptionsCssModule;
