// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreatePushNotificationCssNamespace {
  export interface ICreatePushNotificationCss {
    content: string;
    form: string;
    preview: string;
    sent: string;
    sentIcon: string;
    sentText: string;
  }
}

declare const CreatePushNotificationCssModule: CreatePushNotificationCssNamespace.ICreatePushNotificationCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreatePushNotificationCssNamespace.ICreatePushNotificationCss;
};

export = CreatePushNotificationCssModule;
