// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreatePushNotificationPreviewCssNamespace {
  export interface ICreatePushNotificationPreviewCss {
    battery: string;
    container: string;
    deviceInner: string;
    icon: string;
    mock: string;
    notification: string;
    notificationBody: string;
    notificationContent: string;
    notificationHeader: string;
    notificationHeaderImage: string;
    notificationHeaderName: string;
    notificationImage: string;
    notificationImagePlaceholder: string;
    notificationMain: string;
    notificationTitle: string;
    notificationUrl: string;
    notificationUrlIcon: string;
    statusBar: string;
    time: string;
    warning: string;
  }
}

declare const CreatePushNotificationPreviewCssModule: CreatePushNotificationPreviewCssNamespace.ICreatePushNotificationPreviewCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreatePushNotificationPreviewCssNamespace.ICreatePushNotificationPreviewCss;
};

export = CreatePushNotificationPreviewCssModule;
