// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InputOfflineContentCssNamespace {
  export interface IInputOfflineContentCss {
    addUrl: string;
    addUrlContainer: string;
    addUrlError: string;
    addUrlInput: string;
    addUrlTitle: string;
    buttonAdd: string;
    buttonRemove: string;
    list: string;
    listEntry: string;
    url: string;
  }
}

declare const InputOfflineContentCssModule: InputOfflineContentCssNamespace.IInputOfflineContentCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InputOfflineContentCssNamespace.IInputOfflineContentCss;
};

export = InputOfflineContentCssModule;
