// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ShadowBoxCssNamespace {
  export interface IShadowBoxCss {
    box: string;
    content: string;
    header: string;
    loader: string;
    shadow: string;
    shadowbox: string;
    shadowboxSmall: string;
    title: string;
  }
}

declare const ShadowBoxCssModule: ShadowBoxCssNamespace.IShadowBoxCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ShadowBoxCssNamespace.IShadowBoxCss;
};

export = ShadowBoxCssModule;
